[chatting]
chat-template-kwargs = {"enable_thinking":false, "preserve_thinking":true, "reasoning_effort": "none"}
reasoning = off
temperature=0.7
top_p=0.80
top_k=20
min_p=0.0
presence_penalty=1.5
repetition_penalty=1.0

; Non-thinking mode for task execution
; Qwen recommend: instruct (non-thinking) for reasoning tasks
[instruct]
chat-template-kwargs = {"enable_thinking":false, "preserve_thinking":true, "reasoning_effort": "none"}
reasoning = off
temperature=0.7
top_p=0.80
top_k=20
min_p=0.0
presence_penalty=1.5
repetition_penalty=1.0

; Thinking mode for general tasks
; Unsloth recommended: thinking mode general tasks
[thinking]
chat-template-kwargs = {"enable_thinking":true, "preserve_thinking":true, "reasoning_effort": "medium"}
reasoning = on
temperature=1.0
top-p=0.95
top-k=20
min-p=0.0
presence-penalty=0.0
repetition-penalty=1.0

; Thinking mode tuned for precise coding
; Unsloth recommended: thinking mode precise coding tasks
[coding]
chat-template-kwargs = {"enable_thinking":true, "preserve_thinking":true, "reasoning_effort": "xhigh"}
reasoning = on
temperature=1.0
top-p=0.95
top-k=20
min-p=0.0
presence-penalty=0.0
repetition-penalty=1.0
